platform :ios, '9.0'

use_frameworks!

def shared_pods
    pod 'AFNetworking', '~> 3.0.4'
    pod 'FLEX', '~> 2.2.0'
    pod 'Mantle', '~> 2.0.6'
    pod 'PureLayout', '~> 3.0.1'
    pod 'SDWebImage', '~> 3.7.5'
    pod 'Reachability', '~> 3.2'
    pod 'MBProgressHUD', '~> 0.9.2'
end

target 'Basketball' do
    shared_pods
pod 'MONActivityIndicatorView'
end

target 'BasketballTests' do
    shared_pods
end

target 'BasketballUITests' do
    shared_pods
end
