# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Basketball' do

pod 'AFNetworking', '~> 3.0.4'
pod 'FLEX', '~> 2.2.0'
pod 'Mantle', '~> 2.0.6'
pod 'PureLayout', '~> 3.0.1'
pod 'SDWebImage', '~> 3.7.5'
pod 'Reachability', '~> 3.2'
pod 'MBProgressHUD', '~> 0.9.2'

end

target 'BasketballTests' do

end

target 'BasketballUITests' do

end

