platform :ios, '9.0'

use_frameworks!

def shared_pods
    pod 'AFNetworking', '~> 3.0.4'
    pod 'FLEX', '~> 2.2.0'
    pod 'Mantle', '~> 2.0.6'
    pod 'Masonry', '~> 0.6.4'
    pod 'SDWebImage', '~> 3.7.5'
    pod 'Reachability', '~> 3.2'
    pod 'MBProgressHUD', '~> 0.9.2'
    pod 'CocoaLumberjack', '~> 2.2.0'
    pod 'FMDB', '~> 2.6'
    pod 'MONActivityIndicatorView'
    pod 'Charts', '~> 2.2.3'
end

target 'Basketball' do
    shared_pods
end

target 'BasketballTests' do
    shared_pods
end

target 'BasketballUITests' do
    shared_pods
end
